alias c='clear'
alias p='pwd'
alias h='history'
alias x='exit'
alias pyclean='find . -name "*.pyc" -exec rm {} \;'
alias trimright='sed -ie "s/ \{1,\}$//"'
if [ "`which plantuml`" == '' ]; then
    alias plantuml='java -jar ~/Downloads/plantuml.jar'
fi
