#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    if [ -r ~/.dircolors ]; then
        eval "$(dircolors -b ~/.dircolors)"
    else
        eval "$(dircolors -b)"
    fi
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias c='clear'
alias p='pwd'
alias h='history'
alias x='exit'
alias pyclean='find . -name "*.pyc" -exec rm {} \;'
alias trimright='sed -ie "s/ \{1,\}$//"'
if ! hash plantuml 2>/dev/null; then
    alias plantuml='java -jar ~/Downloads/plantuml.jar'
fi

alias docker-codeclimate='docker run -it --rm --env CODECLIMATE_CODE="$PWD" -v "$PWD":/code -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/cc:/tmp/cc codeclimate/codeclimate'

alias avro-tools='java -jar ~/Downloads/avro-tools-1.8.1.jar'

alias swagger-editor='docker run -it --rm -p 8080:8080 swaggerapi/swagger-editor'
alias docker-rake-build='docker run -it --rm -v $(pwd):/root -w /root ruby:2.3 bash -c "bundle install &&  bundle exec rake spec build"'
alias portainer="docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock -v ${HOME}/portainer:/data portainer/portainer"
alias docker-on-docker='docker run -it --rm -v /var/run/docker.sock:/var/run/docker.sock docker'

alias consul-agent-dev='docker run -d --name consul-agent-dev --rm -p 8500:8500 consul:1.7.3 agent -dev -client=0.0.0.0'
alias consul='docker exec consul-agent-dev consul'
