# Taps
tap 'homebrew/bundle'
tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'homebrew/completions'
tap 'homebrew/core'

brew 'caskroom/cask/brew-cask'
cask_args appdir: '/Applications'

# Utils
brew 'ant'
brew 'bash'
  brew 'readline'
brew 'shellcheck'
brew 'cmake'
brew 'coreutils'
#PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
#MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"
brew 'dos2unix'
brew 'grc'
brew 'ipcalc'
brew 'ossp-uuid'
brew 'tree'
brew 'pstree'
brew 'wget'
  brew 'openssl'
brew 'ssh-copy-id'
brew 'git'
brew 'git-review'
cask 'github-desktop'
brew 'bazaar'
brew 'bash-completion'
brew 'plantuml'
  brew 'graphviz'
    brew 'libpng'
    brew 'freetype' #optional
    brew 'librsvg'
#cask 'yed'
brew 'terminal-notifier'

# Languages
brew 'ansible'
  brew 'libyaml'
brew 'go'
cask 'java'
brew 'python'
  brew 'sqlite'
  brew 'gdbm'
brew 'ruby'

# IDEs
cask 'eclipse-ide'
brew 'emacs', args: ['with-cocoa', 'with-gnutls']
  brew 'gnutls'
cask 'iterm2'

# Browsers
cask 'firefox'
cask 'google-chrome'
cask 'google-photos-backup'

# Apps
cask 'filezilla'
cask 'vnc-viewer'

cask 'virtualbox'
cask 'vagrant'
brew 'vagrant-completion'
#cask 'vagrant-manager'
brew 'docker'
brew 'docker-compose'
  brew 'libyaml'
brew 'docker-machine'
cask 'dockertoolbox'
brew 'rancher-compose'

brew 'kdiff3'
  brew 'qt'
cask 'flux'
cask 'skype'

# Fonts
cask 'font-inconsolata'

#node js
brew 'node'
